config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :permits

  resources :types

  resources :categories

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get 'about' => 'home#about'
  get 'contact'=>'home#contact'
  get 'news'=>'home#news'


  get 'starting' => 'home#starting', :as=>'starting'
  get 'running' => 'home#running', :as=>'running'

  #selected a business

  get 'starting/:type' => 'home#showStarting', :as=>'showStarting'
  get 'running/:type' => 'home#showRunning', :as=>'showRunning'
  get 'report' => 'home#report', :as=>'report'
  devise_for :users
  resources :users
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    authorize! :edit, @user, :message => 'Not authorized as an administrator.'
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= simple_form_for(@type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="field">
    <%= f.label :categories %>
    <%= collection_select(:type, :category_id, Category.all, :id, :name, :prompt=>"Please select the category") %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Name</th>
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
    <th></th>
    <th></th>
    <th></th>
    <% end %><% end %>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.name %></td>
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %><%end%>
  </tr>
<% end %>
</table>

<br />
<% if user_signed_in? %>
<% if current_user.has_role? :admin %>
<%= link_to 'New Type', new_type_path %>
<% end %><% end %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<% if user_signed_in? %><% if current_user.has_role :admin %>
<%= link_to 'Edit', edit_type_path(@type) %> |
<% end%><%end%>
<%= link_to 'Back', types_path %>