config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :permits

  resources :types

  resources :categories

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get 'about' => 'home#about'
  get 'contact'=>'home#contact'
  get 'news'=>'home#news'


  get 'starting' => 'home#starting', :as=>'starting'
  get 'running' => 'home#running', :as=>'running'

  #selected a business

  get 'starting/:type' => 'home#showStarting', :as=>'showStarting'
  get 'running/:type' => 'home#showRunning', :as=>'showRunning'
  get 'report' => 'home#report', :as=>'report'
  devise_for :users
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def about

  end
  def contact

  end
  def news

  end
  #Starting or Running a business
  def starting
    @categories = Category.all
  end
  def showStarting
    type = Type.find_by_name(params[:type].capitalize)
    @permits = Permit.all(:include=>:types,
      :conditions=>["types.id=? AND permits.city=?", type, "Houston"]
    )
  end
  def running
    @categories = Category.all
  end
  def showRunning
    type = Type.find_by_name(params[:type].capitalize)
    @permits = Permit.all(:include=>:types,
      :conditions=>["types.id=? AND permits.city=?", type, "Houston"]
    )
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_permits.html.erb
<% @permits.each do |permit| %>
<div class="row">
  <div class="span4">
    <%= link_to permit.name, permit %>
  </div>
  <div class="span6">
    <p><%= permit.description %></p>
  </div>
</div>
<% end %>

app/views/home/about.html.erb
<h1>About Us</h1>
<div class="text span10 offset1">
<h3>We love small business owners. We hate headaches.
</h3><p>
PermitMe! brings together all the permits you need to start a bar. Or a restaurant.
</p><p>
Some business owners want to keep tabs on the permits they already have or the permits they might need. We keep things simple, up to date, and useful.
</p><p>
Whatever dream you want to bring to reality, we help you deal with the not-so-sexy-but-still-important stuff.
</p><h4>
Hit the ground running. We've got your back.
</h4>
</div>

app/views/home/contact.html.erb
<h1>Contact Us</h1>
<div class="text span10 offset1">

</div>

app/views/home/index.html.erb
<div class="row">
  <%= image_tag "STARTHERE.png" %>
</div>
<div class="padding"></div>
<div class="row">
  <div class="window1 span4 offset2">
    I'm Starting a Business.
    <%= link_to image_tag("StartingButton.png"), starting_path, :id=>"starting" %>
  </div>
  <div class="seperator span1">
   <%= image_tag('betweenBtnArrows.png', :class => 'padTop') %>
  </div>
  <div class="window2 span4">
    I'm Running a Business.
    <%= link_to image_tag("RunningButton.png"), running_path, :id=>"running" %>
  </div>
</div>
<div class="padding"><div class="divide"></div></div>
<div class="row">
  <div class="span4">
    <center><%= image_tag "casestudyIcon2.png" %></center>
  </div>
  <div class="span4">
    <center><%= image_tag "casestudyIcon1.png" %></center>
  </div>
  <div class="span4">
    <center><%= image_tag "casestudyIcon3.png" %></center>
  </div>
</div>
<div class="padding"></div>
<div class="row">
  <div class="span4 testimonial">
    <p>Georgina Dawn is a chef-turned-bar owner. Bringing the exotic spirits of the Caribbean down to Houston was her dream come true. She maintains her permits like her business, with a loving & watchful eye. We'll drink to that.</p>
  </div>
  <div class="span4 testimonial">
    <p>Jason Baker wants to launch Baker's Dozen, a high-end restaurant that serves dessert first. Great idea. We surprised him by pointing out 2 permits he didn't know he needed to have. Piece of cake.</p>
  </div>
  <div class="span4 testimonial">
    <p>Alexx & Morgan aren't from Houston, but expanding their franchise to Space City is something they're considering. We respected their time by showing them which permits were time-sensitive. Welcome to Texas.</p>
  </div>
</div>
<div class="padding"><div class="divide"></div></div>
<div class="row">
  <div class="span10 offset1 padding">
    <%= link_to image_tag("contributeBtn.png"), report_path %>
  </div>
</div>

app/views/home/news.html.erb
<h1>News</h1>
<div class="text span10 offset1">

</div>

app/views/home/running.html.erb
<div class="accordian" id="accordion1">
<% @categories.each do |category| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse<%= category.id %>">
        <h4><%= category.name %></h4>
      </a>
    </div>
    <div id="collapse<%= category.id %>" class="accordian-body collapse">
      <div class="accordian-inner">
        <hr>
        <ul>
          <% category.types.each do |type| %>
          <li><%= link_to type.name, running_path + '/' + type.name.downcase %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/home/showRunning.html.erb
<%= render 'permits' %>

app/views/home/showStarting.html.erb
<%= render 'permits' %>

app/views/home/starting.html.erb
<div class="accordian" id="accordion1">
<% @categories.each do |category| %>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapse<%= category.id %>">
        <h4><%= category.name %></h4>
      </a>
    </div>
    <div id="collapse<%= category.id %>" class="accordian-body collapse">
      <div class="accordian-inner">
        <hr>
        <ul>
          <% category.types.each do |type| %>
          <li><%= link_to type.name, starting_path + '/' + type.name.downcase %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
</div>