config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :permits

  resources :types

  resources :categories

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get 'about' => 'home#about'
  get 'contact'=>'home#contact'
  get 'news'=>'home#news'


  get 'starting' => 'home#starting', :as=>'starting'
  get 'running' => 'home#running', :as=>'running'

  #selected a business

  get 'starting/:type' => 'home#showStarting', :as=>'showStarting'
  get 'running/:type' => 'home#showRunning', :as=>'showRunning'
  get 'report' => 'home#report', :as=>'report'
  devise_for :users
  resources :users
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :types

  default_scope order('name ASC')
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    authorize! :new, @user, :message => 'Not authorized as an administrator.'
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    authorize! :edit, @user, :message => 'Not authorized as an administrator.'
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    authorize! :create, @user, :message => 'Not authorized as an administrator.'
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
    <th></th>
    <th></th>
    <th></th>
    <% end %><% end %>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %><% end %>
  </tr>
<% end %>
</table>

<br />

    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
<%= link_to 'New Category', new_category_path %>
<% end %><%end%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>
<% if user_signed_in? %>
<% if current_user.has_role? :admin %>
<%= link_to 'Edit', edit_category_path(@category) %> |
<% end %><% end %>
<%= link_to 'Back', categories_path %>