config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :permits

  resources :types

  resources :categories

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get 'about' => 'home#about'
  get 'contact'=>'home#contact'
  get 'news'=>'home#news'


  get 'starting' => 'home#starting', :as=>'starting'
  get 'running' => 'home#running', :as=>'running'

  #selected a business

  get 'starting/:type' => 'home#showStarting', :as=>'showStarting'
  get 'running/:type' => 'home#showRunning', :as=>'showRunning'
  get 'report' => 'home#report', :as=>'report'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%#<%= link_to "Rails3 Bootstrap Devise Cancan", root_path, :class => 'brand' %>
<ul class="nav nav-pills pull-right">
  <li>
    <%= link_to 'About Us', about_path %>
  </li>
  <li>
    <%= link_to 'Contact Us', contact_path %>
  </li>
  <li>
    <%= link_to 'News', news_path %>
  </li>
  <%
=begin
  %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <%
=end
  %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PermitMe" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PermitMe" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <img style="position: absolute; top: 0; right: 0; border: 0;" src="/assets/beta.png" alt="Beta">
    <header class="navbar">
          <%= render 'layouts/navigation' %>
    </header>
    <div class="header container">
      <div id="logo"><%= link_to image_tag("PMlogo.png"), root_path %></div>
      <h2 class="tagline" id="tagline">Permitting made easy</h2>
    </div>
    <div id="main" role="main">
      <div class="container" id="body">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>